# Generated by Django 5.0.2 on 2024-02-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_server_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="memeber",
            new_name="member",
        ),
    ]
